// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLAR6hovEeR-0JL36e-cscRjc8lUjgz70',
    appId: '1:817803956864:web:5b31be079f179378e4cc65',
    messagingSenderId: '817803956864',
    projectId: 'e-bucket-2959d',
    authDomain: 'e-bucket-2959d.firebaseapp.com',
    storageBucket: 'e-bucket-2959d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfn5zujFv66WOMI-wTDraJ7yCaNCXC4mM',
    appId: '1:817803956864:android:12e3c16bc45a4bf0e4cc65',
    messagingSenderId: '817803956864',
    projectId: 'e-bucket-2959d',
    storageBucket: 'e-bucket-2959d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIcfL_4UJdyi5cBPjde7zHY--17me8rqM',
    appId: '1:817803956864:ios:7dec123e8b01f2c6e4cc65',
    messagingSenderId: '817803956864',
    projectId: 'e-bucket-2959d',
    storageBucket: 'e-bucket-2959d.appspot.com',
    androidClientId: '817803956864-d12md29bsjt371tlegklh2d9ndn4vm3l.apps.googleusercontent.com',
    iosClientId: '817803956864-ia09jmuqvuo45ivp564ubdv1sh848ef3.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );
}
